# Generated by Django 4.0.4 on 2022-06-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiry', '0002_alter_inquiry_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='listing_id',
            field=models.IntegerField(),
        ),
    ]
