# Generated by Django 4.0.4 on 2022-06-03 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_alter_listing_category_alter_listing_state'),
        ('inquiry', '0003_alter_inquiry_listing_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inquiry',
            name='listing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listing.listing'),
        ),
    ]
