# Generated by Django 4.0.4 on 2022-05-07 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_listing_is_published_listing_list_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='no_of_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_rating',
            field=models.IntegerField(null=True),
        ),
    ]
