# Generated by Django 4.0.4 on 2022-06-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0003_listing_no_of_rating_listing_total_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='address',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Atividade Física', 'Atividade Física'), ('Vídeo e Edição', 'Vídeo e Edição'), ('Arte', 'Arte'), ('Marketing Digital', 'Marketing Digital'), ('Educação', 'Educação'), ('Tecnologia e Programação', 'Tecnologia e Programação'), ('Design', 'Design'), ('Gastronomia', 'Gastronomia'), ('Música e Áudio', 'Música e Áudio'), ('Serviços Gerais', 'Serviços Gerais'), ('Negócios', 'Negócios')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('RJ', 'Rio de Janeiro'), ('MG', 'Minas Gerais'), ('PE', 'Pernambuco'), ('PR', 'Paraná'), ('CE', 'Ceará'), ('RR', 'Roraima'), ('SP', 'São Paulo'), ('AL', 'Alagoas'), ('RS', 'Rio Grande do Sul'), ('SE', 'Sergipe'), ('MA', 'Maranhão'), ('SC', 'Santa Catarina'), ('RN', 'Rio Grande do Norte'), ('GO', 'Goiás'), ('AP', 'Amapá'), ('DF', 'Distrito Federal'), ('RO', 'Rondônia'), ('MS', 'Mato Grosso do Sul'), ('AM', 'Amazonas'), ('TO', 'Tocantins'), ('ES', 'Espírito Santo'), ('AC', 'Acre'), ('PA', 'Pará'), ('PI', 'Piauí'), ('PB', 'Paraíba'), ('BA', 'Bahia'), ('MT', 'Mato Grosso')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
