# Generated by Django 4.0.4 on 2022-06-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0004_alter_listing_address_alter_listing_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Serviços Gerais', 'Serviços Gerais'), ('Vídeo e Edição', 'Vídeo e Edição'), ('Marketing Digital', 'Marketing Digital'), ('Negócios', 'Negócios'), ('Tecnologia e Programação', 'Tecnologia e Programação'), ('Arte', 'Arte'), ('Música e Áudio', 'Música e Áudio'), ('Atividade Física', 'Atividade Física'), ('Gastronomia', 'Gastronomia'), ('Educação', 'Educação'), ('Design', 'Design')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('AP', 'Amapá'), ('RJ', 'Rio de Janeiro'), ('GO', 'Goiás'), ('MG', 'Minas Gerais'), ('SP', 'São Paulo'), ('TO', 'Tocantins'), ('PI', 'Piauí'), ('SE', 'Sergipe'), ('SC', 'Santa Catarina'), ('AC', 'Acre'), ('MS', 'Mato Grosso do Sul'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('AL', 'Alagoas'), ('MA', 'Maranhão'), ('ES', 'Espírito Santo'), ('DF', 'Distrito Federal'), ('PE', 'Pernambuco'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('CE', 'Ceará'), ('BA', 'Bahia'), ('PA', 'Pará'), ('AM', 'Amazonas'), ('MT', 'Mato Grosso'), ('RR', 'Roraima')], max_length=100),
        ),
    ]
