# Generated by Django 4.0.4 on 2022-06-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0005_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Marketing Digital', 'Marketing Digital'), ('Design', 'Design'), ('Educação', 'Educação'), ('Música e Áudio', 'Música e Áudio'), ('Arte', 'Arte'), ('Tecnologia e Programação', 'Tecnologia e Programação'), ('Gastronomia', 'Gastronomia'), ('Vídeo e Edição', 'Vídeo e Edição'), ('Negócios', 'Negócios'), ('Serviços Gerais', 'Serviços Gerais'), ('Atividade Física', 'Atividade Física')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MA', 'Maranhão'), ('AL', 'Alagoas'), ('PI', 'Piauí'), ('RO', 'Rondônia'), ('RJ', 'Rio de Janeiro'), ('SC', 'Santa Catarina'), ('TO', 'Tocantins'), ('SE', 'Sergipe'), ('RS', 'Rio Grande do Sul'), ('PA', 'Pará'), ('MG', 'Minas Gerais'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('PE', 'Pernambuco'), ('AC', 'Acre'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('SP', 'São Paulo'), ('MS', 'Mato Grosso do Sul'), ('PR', 'Paraná'), ('GO', 'Goiás'), ('CE', 'Ceará'), ('RR', 'Roraima'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('MT', 'Mato Grosso')], max_length=100),
        ),
    ]
