# Generated by Django 4.0.4 on 2022-06-03 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0006_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Marketing Digital', 'Marketing Digital'), ('Negócios', 'Negócios'), ('Tecnologia e Programação', 'Tecnologia e Programação'), ('Design', 'Design'), ('Educação', 'Educação'), ('Música e Áudio', 'Música e Áudio'), ('Serviços Gerais', 'Serviços Gerais'), ('Atividade Física', 'Atividade Física'), ('Arte', 'Arte'), ('Vídeo e Edição', 'Vídeo e Edição'), ('Gastronomia', 'Gastronomia')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MA', 'Maranhão'), ('RR', 'Roraima'), ('MT', 'Mato Grosso'), ('AP', 'Amapá'), ('AL', 'Alagoas'), ('DF', 'Distrito Federal'), ('MS', 'Mato Grosso do Sul'), ('PE', 'Pernambuco'), ('AM', 'Amazonas'), ('CE', 'Ceará'), ('GO', 'Goiás'), ('SE', 'Sergipe'), ('ES', 'Espírito Santo'), ('PI', 'Piauí'), ('SP', 'São Paulo'), ('AC', 'Acre'), ('PR', 'Paraná'), ('BA', 'Bahia'), ('RO', 'Rondônia'), ('PB', 'Paraíba'), ('TO', 'Tocantins'), ('RS', 'Rio Grande do Sul'), ('PA', 'Pará'), ('SC', 'Santa Catarina'), ('MG', 'Minas Gerais'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte')], max_length=100),
        ),
    ]
