# Generated by Django 4.0.4 on 2022-06-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0007_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Tecnologia e Programação', 'Tecnologia e Programação'), ('Serviços Gerais', 'Serviços Gerais'), ('Arte', 'Arte'), ('Vídeo e Edição', 'Vídeo e Edição'), ('Educação', 'Educação'), ('Gastronomia', 'Gastronomia'), ('Design', 'Design'), ('Negócios', 'Negócios'), ('Atividade Física', 'Atividade Física'), ('Música e Áudio', 'Música e Áudio'), ('Marketing Digital', 'Marketing Digital')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('RN', 'Rio Grande do Norte'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('PB', 'Paraíba'), ('RO', 'Rondônia'), ('BA', 'Bahia'), ('RS', 'Rio Grande do Sul'), ('PE', 'Pernambuco'), ('MT', 'Mato Grosso'), ('DF', 'Distrito Federal'), ('PA', 'Pará'), ('AM', 'Amazonas'), ('RR', 'Roraima'), ('MA', 'Maranhão'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('MS', 'Mato Grosso do Sul'), ('RJ', 'Rio de Janeiro'), ('AC', 'Acre'), ('CE', 'Ceará'), ('TO', 'Tocantins'), ('GO', 'Goiás'), ('PR', 'Paraná'), ('ES', 'Espírito Santo'), ('MG', 'Minas Gerais'), ('PI', 'Piauí')], max_length=100),
        ),
    ]
