# Generated by Django 4.0.4 on 2022-06-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0008_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Serviços Gerais', 'Serviços Gerais'), ('Marketing Digital', 'Marketing Digital'), ('Negócios', 'Negócios'), ('Atividade Física', 'Atividade Física'), ('Arte', 'Arte'), ('Tecnologia e Programação', 'Tecnologia e Programação'), ('Educação', 'Educação'), ('Gastronomia', 'Gastronomia'), ('Design', 'Design'), ('Música e Áudio', 'Música e Áudio'), ('Vídeo e Edição', 'Vídeo e Edição')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PR', 'Paraná'), ('RR', 'Roraima'), ('RO', 'Rondônia'), ('PI', 'Piauí'), ('TO', 'Tocantins'), ('AM', 'Amazonas'), ('MA', 'Maranhão'), ('ES', 'Espírito Santo'), ('PB', 'Paraíba'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('RS', 'Rio Grande do Sul'), ('AL', 'Alagoas'), ('SE', 'Sergipe'), ('RN', 'Rio Grande do Norte'), ('SC', 'Santa Catarina'), ('RJ', 'Rio de Janeiro'), ('GO', 'Goiás'), ('PE', 'Pernambuco'), ('SP', 'São Paulo'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('BA', 'Bahia'), ('AC', 'Acre'), ('AP', 'Amapá')], max_length=100),
        ),
    ]
