# Generated by Django 4.0.4 on 2022-06-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0009_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Marketing Digital', 'Marketing Digital'), ('Tecnologia e Programação', 'Tecnologia e Programação'), ('Design', 'Design'), ('Arte', 'Arte'), ('Serviços Gerais', 'Serviços Gerais'), ('Gastronomia', 'Gastronomia'), ('Negócios', 'Negócios'), ('Educação', 'Educação'), ('Música e Áudio', 'Música e Áudio'), ('Vídeo e Edição', 'Vídeo e Edição'), ('Atividade Física', 'Atividade Física')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_1',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_2',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_3',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_4',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_5',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_6',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('SC', 'Santa Catarina'), ('GO', 'Goiás'), ('BA', 'Bahia'), ('RS', 'Rio Grande do Sul'), ('MT', 'Mato Grosso'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PA', 'Pará'), ('MA', 'Maranhão'), ('MS', 'Mato Grosso do Sul'), ('RO', 'Rondônia'), ('AC', 'Acre'), ('DF', 'Distrito Federal'), ('RR', 'Roraima'), ('SP', 'São Paulo'), ('AM', 'Amazonas'), ('MG', 'Minas Gerais'), ('AL', 'Alagoas'), ('RN', 'Rio Grande do Norte'), ('SE', 'Sergipe'), ('CE', 'Ceará'), ('AP', 'Amapá'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('TO', 'Tocantins'), ('ES', 'Espírito Santo'), ('RJ', 'Rio de Janeiro')], max_length=100),
        ),
    ]
