# Generated by Django 4.0.4 on 2022-06-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0010_alter_listing_category_alter_listing_photo_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Atividade Física', 'Atividade Física'), ('Negócios', 'Negócios'), ('Tecnologia e Programação', 'Tecnologia e Programação'), ('Gastronomia', 'Gastronomia'), ('Educação', 'Educação'), ('Música e Áudio', 'Música e Áudio'), ('Marketing Digital', 'Marketing Digital'), ('Arte', 'Arte'), ('Design', 'Design'), ('Serviços Gerais', 'Serviços Gerais'), ('Vídeo e Edição', 'Vídeo e Edição')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.FileField(upload_to='media/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('SE', 'Sergipe'), ('PB', 'Paraíba'), ('RO', 'Rondônia'), ('RN', 'Rio Grande do Norte'), ('MG', 'Minas Gerais'), ('PE', 'Pernambuco'), ('CE', 'Ceará'), ('TO', 'Tocantins'), ('AP', 'Amapá'), ('SP', 'São Paulo'), ('ES', 'Espírito Santo'), ('MT', 'Mato Grosso'), ('RJ', 'Rio de Janeiro'), ('AM', 'Amazonas'), ('PR', 'Paraná'), ('BA', 'Bahia'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('SC', 'Santa Catarina'), ('PI', 'Piauí'), ('PA', 'Pará'), ('MS', 'Mato Grosso do Sul'), ('RR', 'Roraima'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('DF', 'Distrito Federal'), ('RS', 'Rio Grande do Sul')], max_length=100),
        ),
    ]
