# Generated by Django 4.0.4 on 2022-06-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0012_alter_listing_category_alter_listing_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='zipcode',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='address',
            new_name='cidade',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='description',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='city',
            new_name='endereco',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_1',
            new_name='foto_2',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='photo_2',
            new_name='foto_3',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='price',
            new_name='preco',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='title',
            new_name='titulo',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_3',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_4',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_5',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_6',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='photo_main',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='state',
        ),
        migrations.AddField(
            model_name='listing',
            name='categoria',
            field=models.CharField(choices=[('Arte', 'Arte'), ('Gastronomia', 'Gastronomia'), ('Educação', 'Educação'), ('Design', 'Design'), ('Vídeo e Edição', 'Vídeo e Edição'), ('Atividade Física', 'Atividade Física'), ('Música e Áudio', 'Música e Áudio'), ('Tecnologia e Programação', 'Tecnologia e Programação'), ('Negócios', 'Negócios'), ('Marketing Digital', 'Marketing Digital'), ('Serviços Gerais', 'Serviços Gerais')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='estado',
            field=models.CharField(choices=[('GO', 'Goiás'), ('PR', 'Paraná'), ('SE', 'Sergipe'), ('PE', 'Pernambuco'), ('DF', 'Distrito Federal'), ('CE', 'Ceará'), ('MS', 'Mato Grosso do Sul'), ('RJ', 'Rio de Janeiro'), ('PI', 'Piauí'), ('ES', 'Espírito Santo'), ('RN', 'Rio Grande do Norte'), ('PB', 'Paraíba'), ('RR', 'Roraima'), ('RO', 'Rondônia'), ('MA', 'Maranhão'), ('BA', 'Bahia'), ('AC', 'Acre'), ('AL', 'Alagoas'), ('MT', 'Mato Grosso'), ('AM', 'Amazonas'), ('SP', 'São Paulo'), ('SC', 'Santa Catarina'), ('RS', 'Rio Grande do Sul'), ('TO', 'Tocantins'), ('AP', 'Amapá'), ('MG', 'Minas Gerais'), ('PA', 'Pará')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='foto_1',
            field=models.FileField(blank=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
