category_choices = {
  ('Serviços Gerais', 'Serviços Gerais'),
  ('Vídeo e Edição', 'Vídeo e Edição'),
  ('Música e Áudio', 'Música e Áudio'),
  ('Educação', 'Educação'),
  ('Marketing Digital', 'Marketing Digital'),
  ('Arte', 'Arte'),
  ('Tecnologia e Programação', 'Tecnologia e Programação'),
  ('Design', 'Design'),
  ('Negócios', 'Negócios'),
  ('Atividade Física', 'Atividade Física'),
  ('Gastronomia', 'Gastronomia'),
  
  }


state_choices = {
  ('AC', 'Acre'),
  ('AL', 'Alagoas'),
  ('AP', 'Amapá'),
  ('AM', 'Amazonas'),
  ('BA', 'Bahia'),
  ('CE', 'Ceará'),
  ('ES', 'Espírito Santo'),
  ('GO', 'Goiás'),
  ('MA', 'Maranhão'),
  ('MT', 'Mato Grosso'),
  ('MS', 'Mato Grosso do Sul'),
  ('MG', 'Minas Gerais'),
  ('PA', 'Pará'),
  ('PB', 'Paraíba'),
  ('PR', 'Paraná'),
  ('PE', 'Pernambuco'),
  ('PI', 'Piauí'),
  ('RJ', 'Rio de Janeiro'),
  ('RN', 'Rio Grande do Norte'),
  ('RS', 'Rio Grande do Sul'),
  ('RO', 'Rondônia'),
  ('RR', 'Roraima'),
  ('SC', 'Santa Catarina'),
  ('SP', 'São Paulo'),
  ('SE', 'Sergipe'),
  ('TO', 'Tocantins'),
  ('DF', 'Distrito Federal'),
}